#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <ip> <host>"
    exit 1
fi


if [ -z "$2" ]; then
    echo "Usage: $0 <ip> <host>"
    exit 1
fi

HOST=$(echo "$2" | sed 's/\./\\\./g')
CONTENT=$(grep -vwE "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[ ]+$HOST$" /etc/hosts)

echo "$CONTENT" > /etc/hosts
echo "$1    $2" | tee -a /etc/hosts
